# Generated by Django 5.0.3 on 2024-04-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0002_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('System-feature', 'System notification - New feature'), ('System-news', 'System notification - Admin news'), ('Blog-react', 'Blog notification - React'), ('Blog-comment', 'Blog notification - Comment'), ('Blog-share', 'Blog notification - Share'), ('User-friend', 'User notification - Friends'), ('User-task', 'User notification - Task overdue'), ('Other', 'Other notification')], default='Other', max_length=20),
        ),
    ]
