# Generated by Django 5.0.3 on 2024-04-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0005_remove_notification_react_notification_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
