# Generated by Django 5.0.3 on 2024-03-31 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('curr_work', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current work')),
                ('highest_education', models.CharField(blank=True, max_length=100, null=True)),
                ('curr_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Living place')),
                ('phone_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Single', 'Single'), ('Dating', 'Dating'), ('Married', 'Married'), ('Private', 'Private')], max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
